import { DesignStyle, RoomPreset } from "./types";

export const DESIGN_STYLES: DesignStyle[] = [
  {
    id: "scandinavian",
    name: "Scandinavian",
    description: "Bright, airy, functional, and centered on natural materials like light woods and cozy textiles.",
    prompt: "Scandinavian interior style with clean lines, functional layout, light ashwood floor, neutral color palette (white, light grey, beige), a fluffy wool rug, minimal shelving, and lots of soft natural daylight.",
    iconName: "Compass",
  },
  {
    id: "midcentury",
    name: "Mid-Century Modern",
    description: "Classic retro charm featuring organic curves, rich teakwood furniture, and iconic olive/mustard accent tones.",
    prompt: "Mid-Century Modern interior style with rich warm walnut credenza, organic tapered leg furniture, a leather lounge chair, geometric patterned throw pillows, brass lighting accents, and warm earthy tones.",
    iconName: "Armchair",
  },
  {
    id: "bohemian",
    name: "Bohemian Boho",
    description: "Eclectic and layered, combining rattan weaves, vibrant rugs, lush indoor plants, and cozy textile textures.",
    prompt: "Bohemian Boho interior design style, layered moroccan rugs, woven rattan chairs, terracotta flower pots, lush green hanging plants, colorful textured cushions, low-slung lounge seating, and warm ambient string lighting.",
    iconName: "Palmtree",
  },
  {
    id: "industrial",
    name: "Industrial Loft",
    description: "Edgy urban aesthetic defined by exposed brick, concrete surfaces, metal frames, and weathered leather.",
    prompt: "Industrial loft interior style, exposed brick walls, matte black metal framing, concrete structural columns, distressed brown leather chesterfield sofa, Edison bulb pendant lamps, and vintage metal bookshelves.",
    iconName: "Flame",
  },
  {
    id: "minimalist",
    name: "Minimalist Slate",
    description: "Sleek, uncluttered, and focusing on negative space, monochrome palettes, and essential structural lines.",
    prompt: "Minimalist sleek interior design, monochrome light-gray palette, handleless flush cabinetry, a low profile platform sofa, concealed linear lighting, zero clutter, and beautiful large-scale architectural negative space.",
    iconName: "Layers",
  },
];

export const ROOM_PRESETS: RoomPreset[] = [
  {
    id: "living-room",
    name: "Cozy Parlor Lounge",
    description: "A warm, rustic lounge ready for a high-end styled makeover.",
    originalImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    styleImages: {
      scandinavian: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80",
      midcentury: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
      bohemian: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
      industrial: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      minimalist: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80",
    },
    shoppableItems: {
      scandinavian: [
        {
          id: "scand-1",
          name: "Nordic Wool Tassel Area Rug",
          category: "Rug",
          price: "$289",
          brand: "West Elm",
          description: "Hand-woven premium wool rug with characteristic neutral diamond braids and thick corner tassels.",
          link: "https://www.google.com/search?tbm=shop&q=Nordic+Wool+Tassel+Area+Rug+West+Elm",
        },
        {
          id: "scand-2",
          name: "Oatmeal Linen Minimal Sofa",
          category: "Seating",
          price: "$1,150",
          brand: "Article",
          description: "Ultra-comfy clean-lined 3-seater upholstered in premium Belgian flax linen with solid ash legs.",
          link: "https://www.google.com/search?tbm=shop&q=Oatmeal+Linen+Minimal+Sofa+Article",
        },
        {
          id: "scand-3",
          name: "Solid Oak Floating Display Ledge",
          category: "Shelving",
          price: "$59",
          brand: "IKEA",
          description: "Minimalist oak picture shelf ideal for displaying artwork frames without clutter.",
          link: "https://www.google.com/search?tbm=shop&q=Solid+Oak+Floating+Display+Ledge+IKEA",
        },
      ],
      midcentury: [
        {
          id: "mid-1",
          name: "Vintage Teakwood Sideboard Credenza",
          category: "Table",
          price: "$890",
          brand: "West Elm",
          description: "Warm walnut wooden media console with classic retro sliding doors and elegant tapered dowel legs.",
          link: "https://www.google.com/search?tbm=shop&q=Vintage+Teakwood+Sideboard+Credenza+West+Elm",
        },
        {
          id: "mid-2",
          name: "Retro Mustard Ochre Velvet Lounge Chair",
          category: "Seating",
          price: "$450",
          brand: "Article",
          description: "Bold mid-century accent chair finished in dense velvet pile with a brushed-brass wire frame.",
          link: "https://www.google.com/search?tbm=shop&q=Retro+Mustard+Ochre+Velvet+Lounge+Chair+Article",
        },
        {
          id: "mid-3",
          name: "Mid-Century Brass Sphere Floor Lamp",
          category: "Lighting",
          price: "$180",
          brand: "Wayfair",
          description: "Double globes in sandblasted white glass suspended on a slender antique-brass pole.",
          link: "https://www.google.com/search?tbm=shop&q=Mid-Century+Brass+Sphere+Floor+Lamp+Wayfair",
        },
      ],
      bohemian: [
        {
          id: "boho-1",
          name: "Handmade Natural Rattan Accent Chair",
          category: "Seating",
          price: "$210",
          brand: "Wayfair",
          description: "Stunning hand-shaped rattan chair with a deep scoop design and structural iron legs.",
          link: "https://www.google.com/search?tbm=shop&q=Handmade+Natural+Rattan+Accent+Chair+Wayfair",
        },
        {
          id: "boho-2",
          name: "Terracotta Speckled Glaze Indoor Urn",
          category: "Decor",
          price: "$45",
          brand: "IKEA",
          description: "Earthy clay pot with artisanal sandy texture, perfect for holding tall dried pampas or fiddle leaf trees.",
          link: "https://www.google.com/search?tbm=shop&q=Terracotta+Speckled+Glaze+Indoor+Urn+IKEA",
        },
        {
          id: "boho-3",
          name: "Macrame Textured Fringe Pouf Ottoman",
          category: "Seating",
          price: "$75",
          brand: "Target",
          description: "Chunky cotton-braided floor pouf with playful woven braids adding relaxed global texture.",
          link: "https://www.google.com/search?tbm=shop&q=Macrame+Textured+Fringe+Pouf+Ottoman+Target",
        },
      ],
      industrial: [
        {
          id: "ind-1",
          name: "Concord Distressed Brown Chesterfield Sofa",
          category: "Seating",
          price: "$1,450",
          brand: "Wayfair",
          description: "Stately button-tufted 3-seater wrapped in rich pull-up oiled top-grain leather with iron rivet accents.",
          link: "https://www.google.com/search?tbm=shop&q=Concord+Distressed+Brown+Chesterfield+Sofa+Wayfair",
        },
        {
          id: "ind-2",
          name: "Matte Black Multi-Joint Edison Wall Sconce",
          category: "Lighting",
          price: "$85",
          brand: "Restoration Hardware",
          description: "Industrial swing-arm lamp with raw metal mechanics and gold-tinted amber filament bulb.",
          link: "https://www.google.com/search?tbm=shop&q=Matte+Black+Multi+Joint+Edison+Wall+Sconce",
        },
      ],
      minimalist: [
        {
          id: "min-1",
          name: "Monolithic Charcoal Concrete Coffee Table",
          category: "Table",
          price: "$499",
          brand: "CB2",
          description: "Brutalist block table cast from lightweight fibrous grey concrete with a sleek micro-seal coating.",
          link: "https://www.google.com/search?tbm=shop&q=Monolithic+Charcoal+Concrete+Coffee+Table+CB2",
        },
        {
          id: "min-2",
          name: "Concealed Warm White LED Floor Strip",
          category: "Lighting",
          price: "$65",
          brand: "Philips Hue",
          description: "Dimmable flexible smart bar that washes walls in beautiful, warm indirect cove light.",
          link: "https://www.google.com/search?tbm=shop&q=Concealed+Warm+White+LED+Floor+Strip+Philips",
        },
      ],
    },
  },
  {
    id: "bedroom",
    name: "Classic Dormer Bedroom",
    description: "An unadorned, simple bedroom with a dormer wall waiting for styling structure.",
    originalImage: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    styleImages: {
      scandinavian: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80",
      midcentury: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      bohemian: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
      industrial: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      minimalist: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1200&q=80",
    },
    shoppableItems: {
      scandinavian: [
        {
          id: "scand-b1",
          name: "Linen Duvet Cover Set in Bone White",
          category: "Textiles",
          price: "$169",
          brand: "Brooklinen",
          description: "Eco-certified French flax linen duvet cover that gets softer with every wash. Crisp and breathable.",
          link: "https://www.google.com/search?tbm=shop&q=Linen+Duvet+Cover+Set+Brooklinen",
        },
        {
          id: "scand-b2",
          name: "Oak Dowel Leg Nightstand",
          category: "Table",
          price: "$199",
          brand: "Article",
          description: "Solid oak table with a single soft-close drawer and open lower shelf space for reading books.",
          link: "https://www.google.com/search?tbm=shop&q=Oak+Dowel+Leg+Nightstand+Article",
        },
      ],
      midcentury: [
        {
          id: "mid-b1",
          name: "Tapered Spindle Oak Platform Bed",
          category: "Bed",
          price: "$799",
          brand: "West Elm",
          description: "Solid wooden headboard styled with sleek geometric spindles, tapering retro legs, and organic lines.",
          link: "https://www.google.com/search?tbm=shop&q=Tapered+Spindle+Oak+Platform+Bed+West+Elm",
        },
      ],
      bohemian: [
        {
          id: "boho-b1",
          name: "Woven Rattan Sunburst Headboard",
          category: "Bed",
          price: "$250",
          brand: "Urban Outfitters",
          description: "Fabulous hand-braided giant fan silhouette styled with natural split reed and rattan skin wrapping.",
          link: "https://www.google.com/search?tbm=shop&q=Woven+Rattan+Sunburst+Headboard",
        },
      ],
      industrial: [
        {
          id: "ind-b1",
          name: "Black Cast Iron Pipeline Canopy Bed Frame",
          category: "Bed",
          price: "$580",
          brand: "Wayfair",
          description: "Sturdy black carbon steel pipe joint structure giving a lofty urban structural aesthetic.",
          link: "https://www.google.com/search?tbm=shop&q=Black+Cast+Iron+Pipeline+Canopy+Bed+Frame",
        },
      ],
      minimalist: [
        {
          id: "min-b1",
          name: "Floating Japanese Low Zen Bed Base",
          category: "Bed",
          price: "$420",
          brand: "Tatami Room",
          description: "Low height solid ash platform bed designed with traditional joint locking, no metallic screws.",
          link: "https://www.google.com/search?tbm=shop&q=Floating+Japanese+Low+Zen+Bed+Base",
        },
      ],
    },
  },
];
